INFO  2022-07-27 16:30:28,709 minitest.py _miniSetUp      241 =========Current case: test_03_pre_cancel=========
INFO  2022-07-27 16:30:28,710 minitest.py _miniSetUp      242 package info: E:.PycharmProjects.hj_xcx.case.test_order, case info: TestOrder.test_03_pre_cancel
INFO  2022-07-27 16:30:28,710 basenative.py wrapper         22  call BaseNative.back_to_miniprogram
INFO  2022-07-27 16:30:28,711 basenative.py back_to_miniprogram 476 try back_to_miniprogram 3
INFO  2022-07-27 16:30:28,711 basenative.py wrapper         26  call BaseNative.back_to_miniprogram end
INFO  2022-07-27 16:30:28,712 app.py     relaunch        297 ReLaunch: /pages/loadPage/index
WARNI 2022-07-27 16:30:33,765 app.py     relaunch        300 ReLaunch(/pages/loadPage/index) but(/pages/makeAnAppointment/index)
INFO  2022-07-27 16:30:33,771 minitest.py capture         523 capture setup.png
INFO  2022-07-27 16:30:33,775 basenative.py wrapper         22  call IdeNative.screen_shot
INFO  2022-07-27 16:31:34,424 minitest.py capture         523 capture setup.png
INFO  2022-07-27 16:31:34,427 basenative.py wrapper         22  call IdeNative.screen_shot
INFO  2022-07-27 16:32:35,061 minitest.py capture         523 capture teardown.png
INFO  2022-07-27 16:32:35,061 basenative.py wrapper         22  call IdeNative.screen_shot
INFO  2022-07-27 16:33:35,629 minitest.py capture         523 capture teardown.png
INFO  2022-07-27 16:33:35,631 basenative.py wrapper         22  call IdeNative.screen_shot
ERROR 2022-07-27 16:34:37,254 minitest.py _miniTearDown   482 [call App.captureScreenshot] receive from remote timeout, id: c8789ca7-652b-496e-946c-8b253f905615
Traceback (most recent call last):
  File "e:\software\python\lib\site-packages\minium\framework\minitest.py", line 476, in _miniTearDown
    retry(2)(self.capture)("teardown")
  File "e:\software\python\lib\site-packages\minium\utils\utils.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "e:\software\python\lib\site-packages\minium\framework\minitest.py", line 524, in capture
    self.native.screen_shot(path)
  File "e:\software\python\lib\site-packages\minium\native\wx_native\basenative.py", line 23, in wrapper
    result = func(*args, **kwargs)
  File "e:\software\python\lib\site-packages\minium\native\wx_native\idenative.py", line 28, in screen_shot
    self.mini.app.screen_shot(filename, return_format)
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\app.py", line 128, in screen_shot
    b64_data = self.connection.send("App.captureScreenshot").get("result").get("data")
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 185, in send
    return self._receive_response(cmd)
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 214, in _receive_response
    raise MiniTimeoutError(
minium.framework.exception.MiniTimeoutError: [call App.captureScreenshot] receive from remote timeout, id: c8789ca7-652b-496e-946c-8b253f905615
ERROR 2022-07-27 16:34:37,257 assertbase.py _teardown_collect 271 <bound method TestOrder.test_03_pre_cancel of <case.test_order.TestOrder testMethod=test_03_pre_cancel>>
Traceback (most recent call last):
  File "e:\software\python\lib\site-packages\minium\framework\libs\unittest\case.py", line 29, in testPartExecutor
    yield
  File "e:\software\python\lib\site-packages\minium\framework\libs\unittest\case.py", line 103, in run
    self._miniSetUp()
  File "e:\software\python\lib\site-packages\minium\framework\minitest.py", line 272, in _miniSetUp
    retry(2)(self.capture)("setup")
  File "e:\software\python\lib\site-packages\minium\utils\utils.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "e:\software\python\lib\site-packages\minium\framework\minitest.py", line 524, in capture
    self.native.screen_shot(path)
  File "e:\software\python\lib\site-packages\minium\native\wx_native\basenative.py", line 23, in wrapper
    result = func(*args, **kwargs)
  File "e:\software\python\lib\site-packages\minium\native\wx_native\idenative.py", line 28, in screen_shot
    self.mini.app.screen_shot(filename, return_format)
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\app.py", line 128, in screen_shot
    b64_data = self.connection.send("App.captureScreenshot").get("result").get("data")
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 185, in send
    return self._receive_response(cmd)
  File "e:\software\python\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 214, in _receive_response
    raise MiniTimeoutError(
minium.framework.exception.MiniTimeoutError: [call App.captureScreenshot] receive from remote timeout, id: ebabdcd3-fbea-47a8-8a12-0c8e0c39c251
